recommendation dao, dto 수정
ryuyeonkyoung/routinemate pull request #19
Opened 2024-11-30 13:23 UTC by seongexn

2024-11-30 16:59 UTC, milkaisgoody reviewed
에러났던 부분이 모두 잘 해결된 것 같습니다.

2024-12-02 14:57 UTC, ryuyeonkyoung requested changes

2024-12-02 14:57 UTC, ryuyeonkyoung commented on src/main/java/model/dao/RecommendationDAO.java
> +        String sql = "SELECT * FROM RECOMMENDATION_TEMPLATES WHERE type = ?";
RECOMMENDATION_TEMPLATES가 어떤 테이블인지 알 수 있을까요?
db 설계 단계에서 못 보던 테이블이여서요!

2024-12-02 14:57 UTC, ryuyeonkyoung commented on src/main/java/model/domain/Recommendation.java
> +    private List<String> eveningRoutineForEveningType; // 저녁형 저녁 루틴
자료형을 Task List에서 String List로 변경하신 이유를 여쭤봐도 될까요??
저는 유지보수성 측면에서는 Task List가 좋을 것 같다고 생각하는데, db에 저장하기에는 String타입이 편하다는 장점도 있어서 성은님 의견을 듣고 싶습니다.
그리고 회원가입을 할 때 아침형인지 저녁형인지만 체크하기로 해서, noon 관련 필드는 삭제하셔도 될 것 같습니다!

2024-12-02 14:57 UTC, ryuyeonkyoung commented on src/main/java/model/dao/RecommendationDAO.java
> -                    recommendation.setEveningRoutineForEveningType(parseTaskIds(rs.getString("eveningRoutineForEveningType")));
조건에 따른 메소드가 잘못 매치되어 있는 것 같습니다. isMorning인 경우에는 setMorning~ 메소드가 들어가야 할 것 같습니다.

2024-12-02 14:57 UTC, ryuyeonkyoung commented on src/main/java/model/dao/RecommendationDAO.java
> -                if ("morning".equals(chronotype)) {
chronotype은 boolean로 자료형이 변경 되기 전의 자료형이여서, 수정이 필요해 보입니다.
밑의 다른 코드에서도 해당 부분이 반영이 안된 것 같습니다.

2024-12-03 13:02 UTC, closed without merging